config/routes.rb
Rails.application.routes.draw do  
  get '/users/search/:query' => 'users#search', as: 'search'
  get '/users/reindex' => 'users#reindex', as: 'reindex'
  resources :users
  

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base  
  include AlgoliaSearch

  algoliasearch do
    attribute :first_name, :last_name, :email
  end
  
  #Geocoder
  geocoded_by :address
  
  def address
    [address_1, address_2, city, state, country].compact.join(', ')
  end
  
  after_validation :geocode
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  #Twilio exception handler
  rescue_from StandardError do |exception|
    trigger_sms_alerts(exception)
  end
  
  def trigger_sms_alerts(e)
    @alert_message = "
      [This is a test] ALERT! 
      It appears the server is having issues. 
      Exception: #{e}. 
      Go to: http://newrelic.com for more details."
    @image_url = "http://howtodocs.s3.amazonaws.com/new-relic-monitor.png"

    @admin_list = YAML.load_file('config/administrators.yml')

    begin
      @admin_list.each do |admin|
        phone_number = admin['phone_number']
        send_message(phone_number, @alert_message, @image_url)
      end
    
      flash[:success] = "Exception: #{e}. Administrators will be notified."
    rescue
      flash[:alert] = "Something when wrong."
    end

    redirect_to '/'
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  def search
    @results = User.raw_search(params[:query])
  end
  
  def reindex
    @reindex = User.reindex
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Deliver the signup email via SendGrid
        UserNotifier.send_signup_email(@user).deliver
        
        # Deliver Twilio SMS
        @twilio_phone_number = ENV['TWILIO_NUMBER']

        @twilio_client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']

        @twilio_client.account.messages.create(
          :from => @twilio_phone_number,
          :to => @user.phone,
          :body => "Hi #{@user.first_name}!  Thanks for signing up!"
        )
        
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :address_1, :address_2, :city, :state, :zip_code, :country, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, http_method=nil)
      class_name = current_page?(link_path) ? 'active' : ''

      content_tag(:li, class: class_name) do
        if http_method
          link_to(link_text, link_path, method: http_method)
        else
          link_to(link_text, link_path)
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
	<head>
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Allan</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

	  <%= csrf_meta_tags %>
	  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	  <!--[if lt IE 9]>
	    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif]-->
	</head>
	<body>
		<div class='container'>
			<%= render 'layouts/navigation_bar' %>
			<br />
			<br />
			<br />
			<%= yield %>
		</div>

	</body>
</html>

app/views/user_notifier/send_signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.first_name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
	<%= f.text_field :first_name, class: "form-control", placeholder: "Harry" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Potter" %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br>
    <%= f.text_field :address_1, class: "form-control", placeholder: "123 Main St." %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br>
    <%= f.text_field :address_2, class: "form-control", placeholder: "Apt. 4321" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control", placeholder: "Vallejo" %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control", placeholder: "CA" %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
   <%= f.text_field :zip_code, class: "form-control", placeholder: "94591" %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control", placeholder: "United States of America" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control", placeholder: "abc@cba.com" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", id: "authy-cellphone" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span12">
		<% @users.each do |user| %>
			<div class="row">
				<div class="span1">
			        <%= user.first_name %>
					<%= user.last_name %>
					<%= user.address_1 %>	
					<%= user.address_2 %>
					<%= user.city %>
					<%= user.state %>
					<%= user.zip_code %>
					<%= user.country %>
					<%= user.email %>
					<%= number_to_phone(user.phone, area_code: true) %>
			  	  	<%= link_to 'Show', user %>
					<%= link_to 'Edit', edit_user_path(user) %>
					<%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
			</div>
		<% end %>
	</div>
</div>

<br />

<div class="row">
	<div class="span1">
		<div class="row">
			<div class="span1">
			    <div class="actions">
			      <%= link_to 'New User', new_user_path, class: "btn btn-default" %>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/reindex.html.erb
<%= @reindex %>

app/views/users/search.html.erb
<% if  @results["nbHits"] == 0 %>
	We found 0 results with "<%= params[:query] %>"
<% else %>
	<% @results["hits"].each do |record| %>
		<%= record["first_name"] %> <%= record["last_name"] %> <%= record["email"] %> <%= link_to 'Show', user_path(record["objectID"]) %>
		<br />
	<% end %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Address_1:</strong>
  <%= @user.address_1 %>
</p>

<p>
  <strong>Address_2:</strong>
  <%= @user.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @user.zip_code %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @user.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.longitude %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@user.phone, area_code: true) %>
</p>

<br />

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCi2m6eZeYQabAIV-5uZGlf16DbWvJCMOs&sensor=false">
</script>
<script type="text/javascript">
  function set_map(state, city){
    var mapOptions = {
      zoom: 12,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"),
    mapOptions);

    if(state == ""){
      address = city;
    }else{
      address = state + ',' + city;
    }

    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({
      'address':address
    },

    function(result, status){
      if (status == google.maps.GeocoderStatus.OK){
        map.setCenter(result[0].geometry.location);

        var marker = new google.maps.Marker({
          map: map,
          position: result[0].geometry.location
        });
      }else{
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
    return false;
  }

  $(document).ready(function(){
    set_map('<%= @user.latitude %>', '<%= @user.longitude %>');
  })
</script>
  
<br />
<br />
<br />
<br />
  

<div id="map-canvas" style="width:300px;height:200px"/>